### ISSUE TITLE
[BUG] 在获取玩加电竞比赛列表时，无法获得今日后信息

### ISSUE THREAD

**Issue by yyyanbj** [ChangxingJiang/CxSpider#13]
在获取玩加电竞比赛列表时，无法获得今日后信息，但实际上是存在该信息的

**Comment by yyyanbj** [comment]
已发pr #14

**Comment by ChangxingJiang** [comment]
嗯嗯，非常感谢！

**Comment by yyyanbj** [comment]
哈哈哈哈项目挺好的，我把这个脚本作为了一个Nonebot的esports插件用于[QQ机器人](https://github.com/beiyuouo/bbot)进行查询，很有帮助233:satisfied:
